### ISSUE TITLE
​

### ISSUE THREAD

**Issue by hello-smile6** [jdev082/Catalyst-Native#1]
​

**Comment by jdev082** [comment]
@hello-smile6 First of all, I require that your PR have an explanation because zero context was given. One word?

**Comment by hello-smile6** [comment]
​

**Comment by jdev082** [comment]
> > @hello-smile6 First of all, I require that your PR have an explanation because zero context was given. One word?
> 
> Not a PR.

Doesn't matter, elaborate.
